/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include "HAL_Gpio.h"
#include "HAL_Usart.h"
#include "HAL_Adc.h"
#include "HAL_Timer.h"
#include "core/CortexM3_Core_Systick.h"

extern USART_TypeDef * Handle;

int __io_putchar(int ch)
{
	HAL_UART_Byte(Handle,ch);
	return ch;
}

void USART_handler(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t flag=1;
uint16_t ADC_Val[2];

//void SystemInit(void)
//{
//	/*----------HSE OSCILLATOR SET---------*/
//	RCC->CR	&= RCC_CLOCK_CONTROL_RESET;//reset everything to select new source Debugger will be lost
//
//	RCC->CR |= RCC_CLOCK_HSE_EN_MSK;
//
//	while(!READ_BIT(RCC->CR,RCC_CLOCK_HSE_READY_POS));
//
//	RCC->CR |= RCC_CLOCK_SECURITY_EN;
//	/*-------------Configure PLL------------*/
//	RCC->CFGR |= RCC_PLL_MUL_9;
//
//	RCC->CFGR &= RCC_PLL_CLK_1;
//
//	RCC->CFGR |= PLLSRC_POS;
//
//	RCC->CFGR |= RCC_PLL_ADC_6;
//
//	RCC->CFGR |= RCC_PLL_APB2_1;
//
//	RCC->CFGR |= RCC_PLL_APB1_2;
//
//	RCC->CFGR |= RCC_PLL_AHB_1;
//
//	RCC->CR   |= RCC_PLL_ENABLE_MSK;
//
//	while(!READ_BIT(RCC->CR,RCC_PLL_READY_POS));
//	/*-----------Select Clock Source----------*/
//	RCC->CFGR |= RCC_CLK_PLL;
//}

uint32_t Delay_Ms=0;
uint8_t Duty_Cycle;
uint16_t Timer_Val;
uint32_t Delay_LED = 0;
uint32_t Delay_LED_O = 0;
void PIN_Pressed(void);
void SYSTICK_INC(void);
uint16_t Counter;
int8_t Key_Pressed='\0';

GPIO_t GPIO_OUT = { .Mode = HAL_GPIO_OUT_PP, .PIN = GPIO_PIN_5, .SPEED =
		HAL_GPIO_SPEED_FREQ_MEDIUM, };
GPIO_t GPIO_OUT2 = { .Mode = HAL_GPIO_OUT_PP, .PIN = GPIO_PIN_6, .SPEED =
		HAL_GPIO_SPEED_FREQ_MEDIUM, };

int main(void)
{
	//SystemInit();/*Trying Something */
	SYSTICK_INIT(SYSTICK_INC,1000000);
	ADC_init_t Adc={
			.ADC_Mode=HAL_ADC_SCHN_AUTO_CONV,
			.Init.Instance=ADC1,
			.Init.Channel_NO=HAL_ADC_CHANNEL_1,
			.Sample_Time={TS_7_5},
			.Init.Alignment=HAL_ADC_ALLIGNMENT_LEFT,
			.Init.Watchdog_EN=HAL_WATCHDOG_DISABLE,
	};
	/*Configure USART */
	UART_t USART={
			.BaudRate=115200,
			.Instance=USART3,
			.Mode=HAL_USART_TRANSMIT_REC_MODE,
			.Parity=HAL_USART_NO_PAIRTY,
			.StopBits=HAL_USART_NO_STOP_BITS_1,
			.WordLength=HAL_USART_WORD_LENGTH_8,
			.RX_Callback=USART_handler,
	};
	TimerU_D_t TIMERX_1={
				.Instance=TIM2,
				.Mode=HAL_TIMER_OP_CMP_MODE,
				.CMP_Modes={HAL_TIMER_OUPUT_CMP_MODE_TOGGLE,HAL_TIMER_OUPUT_CMP_MODE_TOGGLE},
				.ARR_val=0xFFFF,
				.CCR_val={0xFF01},
				.CMP_CHN={HAL_TIMER_CMP_OUT_CHN_4},
				.NO_CMP_CHNS=1,
				.Prescaler=40,
				.SH_EN=HAL_TIMER_SHR_EN,
	};
	GPIO_t GPIO_INT={
			.EDGE_TRIGGER=HAL_GPIO_INT_REDG,
			.EXTI_CLL=PIN_Pressed,
			.EXTI_LINE=EXTI_LINE_0,
			.EXT_N=HAL_GPIO_INT_FLAG_EN,
			.Mode=HAL_GPIO_IN,
			.PULL=HAL_GPIO_NOPULL,
	};
	HAL_Init_PIN(GPIOA,&GPIO_OUT2);
	HAL_Init_PIN(GPIOA,&GPIO_OUT);
	HAL_Init_PIN(GPIOA,&GPIO_INT);
	HAL_UART_Init(&USART);
	HAL_TIMER_init(&TIMERX_1);
	int8_t *Buffer="Ready To TX:";
	HAL_UART_Buffer(USART.Instance,Buffer,12);
	HAL_ADC_Init(&Adc);
	while(1)
	{
		HAL_ADC_READ(&Adc,ADC_Val);
		printf("Timer_Val=%i\n\r",ADC_Val[0]);
	}
}


void SYSTICK_INC(void)
{
	Delay_Ms++;
	Delay_LED = Delay_Ms;
	if (Delay_LED - Delay_LED_O >= 2) {
		HAL_Toggle_PIN(GPIOA, &GPIO_OUT2);
		Delay_LED_O = Delay_LED;
	}
}

void USART_handler(void)
{
	Key_Pressed = USART3->DR;
	if (Key_Pressed == 'a')
		HAL_Write_PIN(GPIOA, &GPIO_OUT, GPIO_SET);
	else if (Key_Pressed == 'b')
		HAL_Write_PIN(GPIOA, &GPIO_OUT, GPIO_RESET);
}

void PIN_Pressed(void){
	Counter++;
}

