/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include "HAL_Gpio.h"
#include "HAL_Usart.h"

int __io_putchar(int ch)
{
	UART3_Send(ch);
	return ch;
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t Key;

int main(void)
{
	/*Configure USART */
	UART_t USART={
			.BaudRate=9600,
			.Instance=USART3,
			.Mode=HAL_USART_TRANSMIT_REC_MODE,
			.Parity=HAL_USART_NO_PAIRTY,
			.StopBits=HAL_USART_NO_STOP_BITS_1,
			.WordLength=HAL_USART_WORD_LENGTH_8,
	};
	GPIO_t LED_Pin={
			.Mode=HAL_GPIO_OUT_PP,
			.PIN=GPIO_PIN_7,
			.SPEED=HAL_GPIO_SPEED_FREQ_LOW,
	};
	HAL_Init_PIN(GPIOB,&LED_Pin);
	HAL_UART_Init(&USART);
	uint8_t *Buffer="Ready To RX:";
	HAL_UART_Buffer(USART.Instance,Buffer,12);
	while(1)
	{
		Key=HAL_UART_ReadByte(USART.Instance);
		if(Key=='a')
		{
			HAL_Write_PIN(GPIOB,&LED_Pin,GPIO_SET);
			HAL_UART_Byte(USART.Instance,'a');
		}
		else if(Key=='b')
		{
			HAL_Write_PIN(GPIOB,&LED_Pin,GPIO_RESET);
			HAL_UART_Byte(USART.Instance,'b');
		}
	}
}


