/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include "HAL_Gpio.h"
#include "HAL_Usart.h"

int __io_putchar(int ch)
{
	UART3_Send(ch);
	return ch;
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	/*Configure USART Output and Input Pins */
	UART_t USART={
			.BaudRate=9600,
			.Instance=USART3,
			.Mode=HAL_USART_TRANSMIT_REC_MODE,
			.Parity=HAL_USART_NO_PAIRTY,
			.StopBits=HAL_USART_NO_STOP_BITS_1,
			.WordLength=HAL_USART_WORD_LENGTH_8,
	};
	HAL_UART_Init(&USART);
	uint8_t *Buffer="Sasa Mix";
	while(1)
	{
		HAL_UART_Buffer(USART.Instance,Buffer,11);
		for(uint32_t i=0;i<=500000;i++);
	}
}


