/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include "HAL_Gpio.h"
#include "HAL_Usart.h"
#include "HAL_Adc.h"
#include "HAL_Timer.h"
#include "core/CortexM3_Core_Systick.h"
#include "HAL_RCC.h"

extern USART_TypeDef * Handle;

int __io_putchar(int ch)
{
	HAL_UART_Byte(Handle,ch);
	return ch;
}

void USART_handler(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void PIN_Pressed(void);
void SYSTICK_INC(void);
void ADC_Handler(void);
void TIM2_CAPT_VAL(void);
void NVIC_int()
{
	SCB->AIRCR = (0x5FA<<16);

	SCB->AIRCR = (0b101<<8);
}

uint16_t Counter;
int8_t Key_Pressed ;
uint16_t CapTure ;
uint8_t flag=1;
uint16_t ADC_Val[2];
uint32_t Delay_Ms=0;
uint8_t Duty_Cycle;
uint16_t Timer_Val;
uint32_t Delay_LED = 0;
uint32_t Delay_LED_O = 0;

RCC_t RCC_REG={
		.ADC_PRESCALER= RCC_PLL_ADC_6,
		.AHB_PRESCALER= RCC_PLL_AHB_1,
		.APB1_PRESCALER= RCC_CLK_PLL_APB_2,
		.APB2_PRESCALER= RCC_CLK_PLL_APB_1,
		.PLLO_MULT= RCC_CLK_PLL_MUL_9,
		.PLL_SRC_SEL= RCC_CLK_PLL_SRC_HSE,
		.SYSCLK_SRC = RCC_CLK_SRC_PLLO,
};

GPIO_t GPIO_OUT = { .Mode = HAL_GPIO_OUT_PP, .PIN = GPIO_PIN_5, .SPEED =
		HAL_GPIO_SPEED_FREQ_MEDIUM, };
GPIO_t GPIO_OUT2 = { .Mode = HAL_GPIO_OUT_PP, .PIN = GPIO_PIN_6, .SPEED =
		HAL_GPIO_SPEED_FREQ_MEDIUM, };

int main(void)
{
	SystemClock_Config(&RCC_REG);
	NVIC_int();
	SYSTICK_INIT(SYSTICK_INC,1000000);
	ADC_init_t Adc={
			.ADC_Mode=HAL_ADC_SCHN_AUTO_CONV,
			.Init.Instance=ADC1,
			.Init.Channel_NO=HAL_ADC_CHANNEL_1,
			.Sample_Time={TS_7_5},
			.Init.Alignment=HAL_ADC_ALLIGNMENT_LEFT,
			.Init.Watchdog_EN=HAL_WATCHDOG_DISABLE,
			.ADC_Callback = ADC_Handler,
	};
	/*Configure USART */
	UART_t USART={
			.BaudRate=115200,
			.Instance=USART3,
			.Mode=HAL_USART_TRANSMIT_REC_MODE,
			.Parity=HAL_USART_NO_PAIRTY,
			.StopBits=HAL_USART_NO_STOP_BITS_1,
			.WordLength=HAL_USART_WORD_LENGTH_8,
			.RX_Callback=USART_handler,
	};
	TimerU_D_t TIMERX_1={
				.Instance=TIM2,
				.Mode=HAL_TIMER_OP_CMP_MODE,
				.CMP_Modes={HAL_TIMER_OUPUT_CMP_MODE_TOGGLE},
				.ARR_val=0xFFFF,
				.CCR_val={0xFF01},
				.CMP_CHN={HAL_TIMER_CMP_OUT_CHN_4},
				.TIMR_CH4_CBCK =TIM2_CAPT_VAL,
				.NO_CMP_CHNS=1,
				.Prescaler=288,
				.SH_EN=HAL_TIMER_SHR_EN,
	};
	GPIO_t GPIO_INT={
			.EDGE_TRIGGER=HAL_GPIO_INT_REDG,
			.EXTI_CLL=PIN_Pressed,
			.EXTI_LINE=EXTI_LINE_0,
			.EXT_N=HAL_GPIO_INT_FLAG_EN,
			.Mode=HAL_GPIO_IN,
			.PULL=HAL_GPIO_NOPULL,
	};
	HAL_Init_PIN(GPIOA,&GPIO_OUT2);
	HAL_Init_PIN(GPIOA,&GPIO_OUT);
	HAL_Init_PIN(GPIOA,&GPIO_INT);
	HAL_UART_Init(&USART);
	HAL_TIMER_init(&TIMERX_1);
	int8_t *Buffer="Ready To TX:";
	HAL_UART_Buffer(USART.Instance,Buffer,12);
	HAL_ADC_Init(&Adc);
	while(1)
	{

	}
}

void TIM2_CAPT_VAL(void)
{
	CapTure = TIM2->CCR4;
}

void SYSTICK_INC(void)
{
	Delay_Ms++;
	Delay_LED = Delay_Ms;
	if (Delay_LED - Delay_LED_O >= 250) {
		HAL_Toggle_PIN(GPIOA, &GPIO_OUT2);
		Delay_LED_O = Delay_LED;
	}
}

void ADC_Handler(void)
{
	ADC_Val[0]=HAL_ADC_READ_INT(ADC1,1,HAL_ADC_ALLIGNMENT_LEFT);
	printf("Timer_Val=%i\n\r", ADC_Val[0]);
}

void USART_handler(void)
{
	Key_Pressed = USART3->DR;
	if (Key_Pressed == 'a')
		HAL_Write_PIN(GPIOA, &GPIO_OUT, GPIO_SET);
	else if (Key_Pressed == 'b')
		HAL_Write_PIN(GPIOA, &GPIO_OUT, GPIO_RESET);
}

void PIN_Pressed(void){
	Counter++;
}

