/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include "HAL_Gpio.h"
#include "HAL_Usart.h"
#include "HAL_Adc.h"
#include "HAL_Timer.h"
#include "core/CortexM3_Core_Systick.h"

extern USART_TypeDef * Handle;

int __io_putchar(int ch)
{
	HAL_UART_Byte(Handle,ch);
	return ch;
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t Key;
uint16_t ADC_Val[2];

//void SystemInit(void)
//{
//	/*----------HSE OSCILLATOR SET---------*/
//	RCC->CR	&= RCC_CLOCK_CONTROL_RESET;//reset everything to select new source Debugger will be lost
//
//	RCC->CR |= RCC_CLOCK_HSE_EN_MSK;
//
//	while(!READ_BIT(RCC->CR,RCC_CLOCK_HSE_READY_POS));
//
//	RCC->CR |= RCC_CLOCK_SECURITY_EN;
//	/*-------------Configure PLL------------*/
//	RCC->CFGR |= RCC_PLL_MUL_9;
//
//	RCC->CFGR &= RCC_PLL_CLK_1;
//
//	RCC->CFGR |= PLLSRC_POS;
//
//	RCC->CFGR |= RCC_PLL_ADC_6;
//
//	RCC->CFGR |= RCC_PLL_APB2_1;
//
//	RCC->CFGR |= RCC_PLL_APB1_2;
//
//	RCC->CFGR |= RCC_PLL_AHB_1;
//
//	RCC->CR   |= RCC_PLL_ENABLE_MSK;
//
//	while(!READ_BIT(RCC->CR,RCC_PLL_READY_POS));
//	/*-----------Select Clock Source----------*/
//	RCC->CFGR |= RCC_CLK_PLL;
//}


int main(void)
{
	//SystemInit();/*Trying Something */
	SYSTICK_INIT();
	ADC_init_t Adc={
			.ADC_Mode=HAL_ADC_SCHN_AUTO_CONV,
			.Init.Instance=ADC1,
			.Init.Channel_NO=HAL_ADC_CHANNEL_1,
			.Sample_Time={TS_7_5},
			.Init.Alignment=HAL_ADC_ALLIGNMENT_LEFT,
			.Init.Watchdog_EN=HAL_WATCHDOG_DISABLE,
	};
	/*Configure USART */
	UART_t USART={
			.BaudRate=115200,
			.Instance=USART3,
			.Mode=HAL_USART_TRANSMIT_REC_MODE,
			.Parity=HAL_USART_NO_PAIRTY,
			.StopBits=HAL_USART_NO_STOP_BITS_1,
			.WordLength=HAL_USART_WORD_LENGTH_8,
	};
	TimerU_D_t TIMERX_1={
				.Instance=TIM2,
				.Mode=HAL_TIMER_OP_CMP_MODE,
				.CMP_Modes={HAL_TIMER_OUPUT_CMP_MODE_TOGGLE,HAL_TIMER_OUPUT_CMP_MODE_ACTIVE},
				.ARR_val=0xFFFF,
				.CCR_val={0xF001,0xF0F0},
				.CMP_CHN={HAL_TIMER_CMP_OUT_CHN_4,HAL_TIMER_CMP_OUT_CHN_1},
				.NO_CMP_CHNS=2,
				.Prescaler=16,
				.SH_EN=HAL_TIMER_SHR_EN,
	};
	HAL_ADC_Init(&Adc);
	HAL_UART_Init(&USART);
	HAL_TIMER_init(&TIMERX_1);
	int8_t *Buffer="Ready To TX:";
	HAL_UART_Buffer(USART.Instance,Buffer,12);
	while(1)
	{
		HAL_ADC_READ(&Adc,&ADC_Val);
		printf("Sensor Voltage_Val=%i\n",ADC_Val[0]);
		SYSTICK_Delay_ms(500);
	}
}


